### ISSUE TITLE
/etc/hosts and /private/etc/hosts

### ISSUE THREAD

**Issue by crahan** [ernw/hardening#5]
Since `/etc/` is a symbolic link to `/private/etc/` on OS X, aren't `/etc/hosts` and `/private/etc/hosts` the same file? I'm not sure what is meant by:

> ! But there is local per User hosts file "/private/etc/hosts"

**Comment by Traxes** [comment]
Hi, 

i added the change in https://github.com/ernw/hardening/commit/a8cff0307cac10f70a08586f6b578dfd5a4978fb

the comment were misleading since SIP restricts access to directories like /System /bin /sbin /usr and not /etc/ (The Symlink is a leftover from NextStep to mount FileSystems as Read-only and /private as writable). 

Thanks for the hint.
